In [18]:
import numpy as np
import matplotlib.pyplot as plt
from random import normalvariate
from numpy.linalg import inv, qr

In [2]:
#线代  dot函数
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1., 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [4]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [5]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

x.dot(y)等价于np.dot(x, y)，是2✖️3与3✖️2的矩阵相乘，最终是2✖️2的矩阵

In [14]:
#二维数组跟一个大小合适的一维数组的矩阵点积运算会得到一维数组
#x
x @ np.ones(3)

array([ 6., 15.])

@ 运算符用于矩阵乘法，也称为点积。
x 是一个 2x3 的矩阵，形状是 (2, 3)
np.ones(3) 是一个一维数组，形状是 (3,)
一维数组在做矩阵乘法时会被认定为列向量
np.ones(3) 有 3 个元素，等价于一个形状为 (3, 1) 的列向量。
所以2x3 与 3x1 的矩阵相乘为 2x1 的矩阵，即将x中的每行相加，最后得到[6, 15]

In [15]:
#为证明np.ones()的用法
test = np.ones(3)
test

array([1., 1., 1.])

In [16]:
test1 = np.ones((3, 1))
#三行一列
test1

array([[1.],
       [1.],
       [1.]])

In [17]:
x @ test1

array([[ 6.],
       [15.]])

x @ np.ones((3, 1)) 与 x @ np.ones(3) 的结果在形状上是不同的，但在数值上是相同的。
x @ np.ones(3):
x 是一个 (2, 3) 形状的矩阵。
np.ones(3) 是一个 (3,) 形状的一维数组。
矩阵乘法结果是一个形状为 (2,) 的一维数组。

x @ np.ones((3, 1)):
x 仍然是一个 (2, 3) 形状的矩阵。
np.ones((3, 1)) 是一个 (3, 1) 形状的二维列向量。
矩阵乘法结果是一个形状为 (2, 1) 的二维数组。

两个数值相同，但形状不同，一个是一维数组，一个是二维数组

In [23]:
#numpy.linalg中有一组标准的矩阵分解运算以及求逆和求行列式方法：
rng = np.random.default_rng(seed=12345)
X = rng.standard_normal((5, 5))
mat = X.T @ X

In [22]:
inv(mat)

array([[ 0.15548538, -0.36723081, -0.52638547, -0.2300642 , -0.04646089],
       [-0.36723081,  2.54917814,  3.47827334,  1.48196722,  0.22206454],
       [-0.52638547,  3.47827334,  5.46389554,  2.46214396,  0.63467543],
       [-0.2300642 ,  1.48196722,  2.46214396,  1.38302896,  0.33430132],
       [-0.04646089,  0.22206454,  0.63467543,  0.33430132,  0.33879566]])