In [6]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

%timeit my_arr2 = my_arr * 2

780 μs ± 11.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
%timeit my_list2 = [x * 2 for x in my_list]

21.6 ms ± 79 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
#numPy中的ndarray：多位数组对象
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [8]:
#二维数据运算
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [9]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [10]:
#ndarray同构数据多维容器，同构数据中的元素必须是相同类型。
#每个数组都有一个shape（用于表示各个维度大小的元组）和一个dtype（数组的数据模型）：
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
#嵌套序列  由一组等长列表组成的列表会被转化为多维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

因为data2是列表的列表，所以numpy数组有arr2有两个维度，它的形状取决于数据。
可以用ndim和shape来确认数组的维度和形状

In [15]:
#维度
arr2.ndim

2

In [16]:
#维度中的个数
arr2.shape

(2, 4)

In [17]:
arr2.dtype

dtype('int64')

除了numpy.array,还有其他一些函数可以创建数组。
比如numpy.zeros和numpy.ones创建指定长度或形状的全0和全1数组。 
numpy.empty可以创建一个没有任何元素的多维数组，只需传入一个表示形状的元组即可

In [2]:
import numpy as np

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros((3, 6))  #三行六列

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
np.empty((2, 3, 2))  #两个三行两列的数组，不建议用empty，因为0可能是垃圾值

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [5]:
#numpy.arange是py内置的range函数的数组版本
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Numpy一般默认是float64
Numpy数组创建函数：P97

![jupyter](./4.1.png)

![jupyter](./4.2.png)

code插入
图片<img src="/Users/dususu/Desktop/srcphoto.png", width=320, heigth=240>

In [7]:
#ndarray的数据类型
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [8]:
arr2.dtype

dtype('int32')

数据类型是Numpy与其他系统灵活交互数据的来源。float占用8字节（64位），因此在Numpy中就是float64

Numpy的数据类型

![jupyter](./4.3.png)

int8：有符号型， 无符号型uint8,只能表示0～255

In [9]:
#通过ndarray的astype方法可以将数组从一种数据类型转换或投射成另一种数据类型
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [10]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [11]:
float_arr.dtype

dtype('float64')

In [12]:
#将浮点转换为整数则小数部分会被截断,不会舍入
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [14]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [16]:
#如果某个字符串数组表示的全是数字，也可以用astype将其转化为数值形式
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(float)
#float 和 np.float64 作用相同，Numpy会将py相同类型映射到等价的dtype上

array([ 1.25, -9.6 , 42.  ])

使用numpy.string_类型时，需要注意的是：因为Numpy的字符串大多数都是大小固定的，截断时不会警告，pandas会给出更好的处理方法，转换过程出错的情况下，比如字符串无法转为float，会抛出valueError

In [2]:
#可以用另一个数组的dtype属性
import numpy as np

int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .300, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#更简洁的代码表示dtype
zeros_uint32 = np.zeros(8, dtype=uint32)